apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: udacity-api
    app.kubernetes.io/component: config-map
  name: udacity-api-config
data:
  POSTGRES_HOST: "database-1.cbjylismv7ii.ap-southeast-1.rds.amazonaws.com"
  POSTGRES_DB: "postgres"
  AWS_BUCKET: "udacity-project-4-923095746266"
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "default"
  JWT_SECRET: "test"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: udacity-api
    app.kubernetes.io/component: secret
  name: udacity-api-db-secrets
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM= #username
  POSTGRES_PASSWORD: cG9zdGdyZXM= #password
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: udacity-api
    app.kubernetes.io/component: secret
  name: udacity-api-aws-secrets
type: Opaque
data:
  credentials: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - image: toannh14/udagram-api-feed:v1
          name: udagram-api-feed
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
          - secretRef:
              name: udacity-api-aws-secrets
              optional: false
          - secretRef:
              name: udacity-api-db-secrets
              optional: false
          - configMapRef:
              name: udacity-api-config
              optional: false
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - image: toannh14/udagram-api-user:v1
          name: udagram-api-user
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
          - secretRef:
              name: udacity-api-aws-secrets
              optional: false
          - secretRef:
              name: udacity-api-db-secrets
              optional: false
          - configMapRef:
              name: udacity-api-config
              optional: false
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - image: toannh14/udagram-frontend:v1
          name: udagram-frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
          - secretRef:
              name: udacity-api-aws-secrets
              optional: false
          - secretRef:
              name: udacity-api-db-secrets
              optional: false
          - configMapRef:
              name: udacity-api-config
              optional: false
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - image: toannh14/udagram-reverseproxy:v1
          name: udagram-reverseproxy
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
          - secretRef:
              name: udacity-api-aws-secrets
              optional: false
          - secretRef:
              name: udacity-api-db-secrets
              optional: false
          - configMapRef:
              name: udacity-api-config
              optional: false
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
  name: udagram-api-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-api-feed
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
  name: udagram-api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-api-user
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
  - name: "80"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-reverseproxy
---
